site_name: Sim4Life FEniCS Plugin
site_description: Documentation and examples for the Sim4Life FEniCS plugin
site_author: Your Name
repo_url: https://github.com/your-org/s4l-plugin-fenics
repo_name: GitHub
docs_dir: .
site_dir: ../site
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - Examples:
      - Quantum Tunneling: examples/quantum_tunneling/README.md
      - Harmonic Oscillator: examples/harmonic_oscillator/README.md
      - Stokes Flow: examples/stokes_flow/README.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
